apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 3
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: yongshin/docker-node-app
        name: web
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_SERVICE_SERVICE_HOST
          value: mongo
